In [101]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, optimizers, losses
import random

In [106]:
def model():
    inputs = keras.Input(shape=(3,))
    x=inputs
    x = layers.Dense(1, kernel_initializer=tf.keras.initializers.Ones(), bias_initializer=tf.keras.initializers.Zeros())(x)
    return keras.Model(inputs=inputs, outputs=x)
tm = model()
tm.summary()

Model: "model_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_14 (InputLayer)       [(None, 3)]               0         
                                                                 
 normalization (Normalizatio  (None, 3)                7         
 n)                                                              
                                                                 
 dense_23 (Dense)            (None, 1)                 4         
                                                                 
Total params: 11
Trainable params: 4
Non-trainable params: 7
_________________________________________________________________


In [107]:
tm.compile(optimizer=optimizers.Adam(), loss=losses.MeanSquaredError())

In [108]:
x = np.asarray([[random.random()*10000, random.random()*10000, random.random()*10000] for i in range(100000)])
y = np.asarray([sum(i)+random.uniform(-1,1) for i in x])

In [109]:
callbacks = [
    keras.callbacks.TensorBoard(log_dir='./logs')
]
history=tm.fit(x, y, epochs=20, batch_size=32, verbose=2, callbacks=callbacks)

Epoch 1/20
3125/3125 - 7s - loss: 1.0281 - 7s/epoch - 2ms/step
Epoch 2/20
3125/3125 - 7s - loss: 0.9096 - 7s/epoch - 2ms/step
Epoch 3/20
3125/3125 - 6s - loss: 0.8532 - 6s/epoch - 2ms/step
Epoch 4/20
3125/3125 - 6s - loss: 0.8391 - 6s/epoch - 2ms/step
Epoch 5/20
3125/3125 - 6s - loss: 0.8967 - 6s/epoch - 2ms/step
Epoch 6/20
3125/3125 - 6s - loss: 0.8898 - 6s/epoch - 2ms/step
Epoch 7/20
3125/3125 - 6s - loss: 0.8668 - 6s/epoch - 2ms/step
Epoch 8/20
3125/3125 - 6s - loss: 0.8618 - 6s/epoch - 2ms/step
Epoch 9/20
3125/3125 - 7s - loss: 0.8845 - 7s/epoch - 2ms/step
Epoch 10/20
3125/3125 - 7s - loss: 0.8821 - 7s/epoch - 2ms/step
Epoch 11/20
3125/3125 - 8s - loss: 0.9005 - 8s/epoch - 2ms/step
Epoch 12/20
3125/3125 - 7s - loss: 0.8554 - 7s/epoch - 2ms/step
Epoch 13/20
3125/3125 - 7s - loss: 0.8936 - 7s/epoch - 2ms/step
Epoch 14/20
3125/3125 - 7s - loss: 0.8261 - 7s/epoch - 2ms/step
Epoch 15/20
3125/3125 - 9s - loss: 0.9113 - 9s/epoch - 3ms/step
Epoch 16/20
3125/3125 - 7s - loss: 0.8594 - 7s/ep

In [110]:
tm.summary()
tm.get_weights()

Model: "model_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_14 (InputLayer)       [(None, 3)]               0         
                                                                 
 normalization (Normalizatio  (None, 3)                7         
 n)                                                              
                                                                 
 dense_23 (Dense)            (None, 1)                 4         
                                                                 
Total params: 11
Trainable params: 4
Non-trainable params: 7
_________________________________________________________________


[array([0., 0., 0.], dtype=float32),
 array([1., 1., 1.], dtype=float32),
 0,
 array([[1.0000257],
        [1.0000503],
        [1.0000854]], dtype=float32),
 array([-0.00759535], dtype=float32)]

In [111]:
tm.predict(np.asarray([[0.1,0.2,0.3]]))

1/1 [==============================] - 0s 43ms/step


array([[0.5924429]], dtype=float32)